In [16]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
np.insert(arr, 1, 10) # array, indice, valor

array([ 1, 10,  2,  3])

In [7]:
a = np.array([[1,2], [3,4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


In [8]:
print(a.sum(axis=0)) # soma verticalmente

[4 6]


In [9]:
print(a.sum(axis=1)) # soma horizontalmente

[3 7]


In [10]:
np.insert(a, 1, 5, axis=1) # inseriu no indice 1 em cada linha 
# horizontalmente através do eixo

array([[1, 5, 2],
       [3, 5, 4]])

In [11]:
# append 

a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
np.append(a, [4,5,6])


array([1, 2, 3, 4, 5, 6])

In [21]:
ma = np.array([[1,2], [3,4]])
ma

array([[1, 2],
       [3, 4]])

In [23]:
np.append(ma, [[5,6]])

array([1, 2, 3, 4, 5, 6])

In [24]:
np.append(a, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# deletando
a3 = np.array([[1,2], [3,4], [5,6]])
a3


array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.delete(a3, 1, axis=0) # deletando horizontalmente

array([[1, 2],
       [5, 6]])

In [30]:
np.delete(a3, 1, axis=1) # deletando verticalmente

array([[1],
       [3],
       [5]])

In [33]:
a4 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
a4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.delete(a4, np.s_[::2], axis=0)

array([[ 4,  5,  6],
       [10, 11, 12]])

In [35]:
# repetir elementos de um array 
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [37]:
np.repeat(a,2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [38]:
np.repeat(a,2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [39]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [40]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [41]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [42]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
b = np.array([[1,2], [3,4]])

In [45]:
np.tile(b, 2) # repeat de linhas

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [46]:
# Dividindo array 
a = np.array([[1,2,3], [4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.array_split(a, 2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [48]:
np.array_split(a, 2, axis=1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [51]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])


In [53]:
arrays = np.array_split(b, 2, axis=0)
for array in arrays:
    print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [54]:
# Criando arrays de zeros e uns
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [55]:
np.zeros((2,2)) # Shape

array([[ 0.,  0.],
       [ 0.,  0.]])

In [56]:
np.zeros((5,5)) 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [57]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [58]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [62]:
# Criando matriz identidade e matrizes quadradas
identidade = np.eye(10)
identidade

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [65]:
# indexação booleana
booleana = np.array([[1,2], [3,4], [5,6]])
booleana

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
booleana[booleana>3]

array([4, 5, 6])

In [69]:
idx = (booleana > 2) ## verifica se cada booleana satisfaz a condição
idx

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [4]:
# concatenar arrays
conA = np.array([[1,2], [3,4]])
conB = np.array([[5,6]])

print(conA)
print(conB)

[[1 2]
 [3 4]]
[[5 6]]


In [6]:
np.concatenate((conA, conB), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
conB.T # Matriz Transposta troca linha por colunas

np.concatenate((conA, conB.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [11]:
# Embaralhar uma sequencia de array
embaralhar = np.arange(10)
embaralhar


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.shuffle(embaralhar)
embaralhar

array([0, 4, 5, 9, 8, 3, 2, 6, 1, 7])

In [18]:
# Gerando array com linspace
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [24]:
np.linspace(start=2.0, stop=3.0, num=25)

array([ 2.        ,  2.04166667,  2.08333333,  2.125     ,  2.16666667,
        2.20833333,  2.25      ,  2.29166667,  2.33333333,  2.375     ,
        2.41666667,  2.45833333,  2.5       ,  2.54166667,  2.58333333,
        2.625     ,  2.66666667,  2.70833333,  2.75      ,  2.79166667,
        2.83333333,  2.875     ,  2.91666667,  2.95833333,  3.        ])

In [ ]:
arr = np.array([[1,2], [2,3], [3,3], [4,4]])