In [1]:
import numpy as np


In [11]:
m1 = np.array([[1,2,3], [4,5,6]])
m2 = np.array([[7,8,9], [10,11,12]])

In [12]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [14]:
m2 / m1

array([[ 7. ,  4. ,  3. ],
       [ 2.5,  2.2,  2. ]])

In [15]:
np.matrix.round(m2 / m1)

array([[ 7.,  4.,  3.],
       [ 2.,  2.,  2.]])

In [16]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
m2 * 10

array([[ 70,  80,  90],
       [100, 110, 120]])

In [18]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [21]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])